### ISSUE TITLE
Is it normal？

### ISSUE THREAD

**Issue by Master-Ye** [pongthang/Atari-breakout-using-DDQN-RL_agent#2]
I have trained for several epochs, but the return does not converge. It even fluctuates widely. Is this normal? 
I want to know why.Thanks a lot！

**Comment by pongthang** [comment]
Sorry for late reply. Did you solve it ?
Even I face the same issue initially and it because of bad configuration. make sure you input images are pre-processed correctly. Initially I was using parameters mentioned in neurip's atari implementation but then I moved to nature's atari implementation and everything worked out. Hope this helps.
